(cl:in-package cup_grabber-srv)
(cl:export '(TAG1-VAL
          TAG1
          POS_X1-VAL
          POS_X1
          POS_Y1-VAL
          POS_Y1
          POS_Z1-VAL
          POS_Z1
          OR_X1-VAL
          OR_X1
          OR_Y1-VAL
          OR_Y1
          OR_Z1-VAL
          OR_Z1
          OR_W1-VAL
          OR_W1
          TAG2-VAL
          TAG2
          POS_X2-VAL
          POS_X2
          POS_Y2-VAL
          POS_Y2
          POS_Z2-VAL
          POS_Z2
          OR_X2-VAL
          OR_X2
          OR_Y2-VAL
          OR_Y2
          OR_Z2-VAL
          OR_Z2
          OR_W2-VAL
          OR_W2
          TAG3-VAL
          TAG3
          POS_X3-VAL
          POS_X3
          POS_Y3-VAL
          POS_Y3
          POS_Z3-VAL
          POS_Z3
          OR_X3-VAL
          OR_X3
          OR_Y3-VAL
          OR_Y3
          OR_Z3-VAL
          OR_Z3
          OR_W3-VAL
          OR_W3
          TAG4-VAL
          TAG4
          POS_X4-VAL
          POS_X4
          POS_Y4-VAL
          POS_Y4
          POS_Z4-VAL
          POS_Z4
          OR_X4-VAL
          OR_X4
          OR_Y4-VAL
          OR_Y4
          OR_Z4-VAL
          OR_Z4
          OR_W4-VAL
          OR_W4
))