(cl:defpackage cup_grabber-srv
  (:use )
  (:export
   "MULTIARPOSE"
   "<MULTIARPOSE-REQUEST>"
   "MULTIARPOSE-REQUEST"
   "<MULTIARPOSE-RESPONSE>"
   "MULTIARPOSE-RESPONSE"
   "ARPOSE"
   "<ARPOSE-REQUEST>"
   "ARPOSE-REQUEST"
   "<ARPOSE-RESPONSE>"
   "ARPOSE-RESPONSE"
  ))

