// Generated by gencpp from file cup_grabber/ARPose.msg
// DO NOT EDIT!


#ifndef CUP_GRABBER_MESSAGE_ARPOSE_H
#define CUP_GRABBER_MESSAGE_ARPOSE_H

#include <ros/service_traits.h>


#include <cup_grabber/ARPoseRequest.h>
#include <cup_grabber/ARPoseResponse.h>


namespace cup_grabber
{

struct ARPose
{

typedef ARPoseRequest Request;
typedef ARPoseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ARPose
} // namespace cup_grabber


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cup_grabber::ARPose > {
  static const char* value()
  {
    return "912562d6fca199e1e3b0bb6f5dd85bf1";
  }

  static const char* value(const ::cup_grabber::ARPose&) { return value(); }
};

template<>
struct DataType< ::cup_grabber::ARPose > {
  static const char* value()
  {
    return "cup_grabber/ARPose";
  }

  static const char* value(const ::cup_grabber::ARPose&) { return value(); }
};


// service_traits::MD5Sum< ::cup_grabber::ARPoseRequest> should match 
// service_traits::MD5Sum< ::cup_grabber::ARPose > 
template<>
struct MD5Sum< ::cup_grabber::ARPoseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cup_grabber::ARPose >::value();
  }
  static const char* value(const ::cup_grabber::ARPoseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cup_grabber::ARPoseRequest> should match 
// service_traits::DataType< ::cup_grabber::ARPose > 
template<>
struct DataType< ::cup_grabber::ARPoseRequest>
{
  static const char* value()
  {
    return DataType< ::cup_grabber::ARPose >::value();
  }
  static const char* value(const ::cup_grabber::ARPoseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cup_grabber::ARPoseResponse> should match 
// service_traits::MD5Sum< ::cup_grabber::ARPose > 
template<>
struct MD5Sum< ::cup_grabber::ARPoseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cup_grabber::ARPose >::value();
  }
  static const char* value(const ::cup_grabber::ARPoseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cup_grabber::ARPoseResponse> should match 
// service_traits::DataType< ::cup_grabber::ARPose > 
template<>
struct DataType< ::cup_grabber::ARPoseResponse>
{
  static const char* value()
  {
    return DataType< ::cup_grabber::ARPose >::value();
  }
  static const char* value(const ::cup_grabber::ARPoseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUP_GRABBER_MESSAGE_ARPOSE_H
